### PR TITLE
frame_larger_than.py: Support DW_TAG_enumeration_type

### LINKED ISSUE #5: missing support for DW_TAG_enumeration_type
I just noticed that @nathanchance reported [here](https://github.com/ClangBuiltLinux/linux/issues/695#issuecomment-825217512):

```sh
$ $ python3 ../../github/frame-larger-than/frame_larger_than.py drivers/gpu/drm/amd/amdgpu/../display/dc/dml/dcn20/display_mode_vba_20.o dml20_ModeSupportAndSystemConfigurationFull
Unsupported type info for DW_TAG_enumeration_type, implement me!
DIE DW_TAG_enumeration_type, size=12, has_children=True
    |DW_AT_type        :  AttributeValue(name='DW_AT_type', form='DW_FORM_ref4', value=75, raw_value=75, offset=638)
    |DW_AT_name        :  AttributeValue(name='DW_AT_name', form='DW_FORM_strp', value=b'dm_validation_status', raw_value=2265, offset=642)
    |DW_AT_byte_size   :  AttributeValue(name='DW_AT_byte_size', form='DW_FORM_data1', value=4, raw_value=4, offset=646)
    |DW_AT_decl_file   :  AttributeValue(name='DW_AT_decl_file', form='DW_FORM_data1', value=1, raw_value=1, offset=647)
    |DW_AT_
```

### PR DESCRIPTION
**Pull request by nathanchance**
Closes: https://github.com/ClangBuiltLinux/frame-larger-than/issues/5

### CODE REVIEW

**Comment by dileks** [comment]
Where is this frame_larger_than.py script from?
Kernel-sources?
CBL's own script/hack?

- Sedat -

**Comment by nathanchance** [comment]
> Where is this frame_larger_than.py script from?
> Kernel-sources?
> CBL's own script/hack?

It is a script that Nick wrote to help debug `-Wframe-larger-than=` instances; it lives in the ClangBuiltLinux organization. If it lived in the kernel sources, I would have sent it as an emailed patch rather than a pull request :)

**Comment by dileks** [comment]
On Thu, Dec 16, 2021 at 12:39 AM Nathan Chancellor
***@***.***> wrote:
>
> Where is this frame_larger_than.py script from?
> Kernel-sources?
> CBL's own script/hack?
>
> It is a script that Nick wrote to help debug -Wframe-larger-than= instances; it lives in the ClangBuiltLinux organization. If it lived in the kernel sources, I would have sent it as an emailed patch rather than a pull request :)
>

Thanks
I re-started my CBL activities recently.
( Currently means build a Clang-LTO v5.15.y kernel when Debian has
released a new 5.15-kernel. )
( LTO/PGO-Optimize my selfmade LLVM-13 toolchain. )
So, I am not up2date in all CBL activities.
Nice to hear it is a CBL selfmade helper-script.
I am mostly interested in DWARF v5 improvements, so I noticed that change.

- Sedat -

**Review by nickdesaulniers — APPROVED** [review]
LGTM thanks! 🆗 🗝️

**Comment by nathanchance** [comment]
Thanks for the review!

**Pull request merged**
